### ISSUE TITLE
Check for i586 instead of i386

### ISSUE THREAD

**Issue by lpsantil** [orlp/pdqsort#1]
When defining rdtsc, you ought to be checking for atleast [i586](http://sourceforge.net/p/predef/wiki/Architectures/) instead of [i386](https://en.wikipedia.org/wiki/Time_Stamp_Counter#Implementation_in_various_processors).

**Comment by orlp** [comment]
I believe I took the `rdtsc` code from this SO question, which uses `__i386__` as well: http://stackoverflow.com/questions/9887839/clock-cycle-count-wth-gcc.

But I guess I can change it.

**Comment by lpsantil** [comment]
I hear ya.  `__i386__` is the "traditional" way of checking for an ia32 processor which is usually good enough for 80% of the time.  The Wikipedia page also indicates some of the issues using the instruction on some of the early Pentium competitors as well.  Nowadays, finding a CPU where the instruction wouldn't work would be difficult, 20 years on from the introduction of the instruction.  However, if the IoT ever really picks up on the Intel [Quarks](https://en.wikipedia.org/wiki/Intel_Quark) & [Curies](http://www.intel.com/content/www/us/en/wearables/wearable-soc.html), Via [Edens](https://en.wikipedia.org/wiki/List_of_VIA_Eden_microprocessors) & [Nanos](https://en.wikipedia.org/wiki/List_of_VIA_Nano_microprocessors), and DM&P [Vortex86s](https://en.wikipedia.org/wiki/Vortex86), you might care at that point.  I can see your sort being useful in those environments.

**Comment by orlp** [comment]
@lpsantil Keep in mind that the sort works fine on any platform, only the benchmark code uses the rdtsc instruction.

**Comment by Morwenn** [comment]
Hasn't the issue been fixed by 23a2a5552a103ea4f476da4ed57cda05ddc69e9d?

**Comment by orlp** [comment]
@Morwenn  I believe so, forgot to close this.
