### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by DBJDBJ** [orlp/pdqsort#12]
Fantastic work. Not an issue more of a question.
standard C++ lib is not "exception free", but I will ask anyway. 
Can we use this lib in "exception free" programs? Using let's say MSVC.

**Comment by billyquith** [comment]
> Fantastic work.

Thank you.

> Can we use this lib in "exception free" programs? Using let's say MSVC.

Games?! 😄 Currently it uses exception handling for reporting errors, although I would like to offer an alternative. This might mean extensive changes to the API (V4?). - Yes I have thought about it, but I have very limited time at the moment.

**Comment by orlp** [comment]
`pdqsort` does not throw exceptions of itself, nor does it allocate memory. The only exceptions that occur while using it is due to trying to sort types that throw on swapping, moving, destructing, etc... or using a throwing comparison function.
