### ISSUE TITLE
pdqsort interface cmake

### ISSUE THREAD

**Issue by damageboy** [orlp/pdqsort#21]
Hi,
I'd like to attempt to sue pdqsort through some package manager for C++ like [CPM](https://github.com/cpm-cmake/CPM.cmake).

To that end, I'd need this repo to incorporate some minimal CMakeLists.txt file that would roughly look like:

```
project(pdqsort CXX)

set(CMAKE_CXX_STANDARD 11)

add_library(pdqsort INTERFACE)
target_include_directories(pdqsort INTERFACE .)
```

This would be sufficient for CPM to figure out what compiler flags to pass to other cmake based projects that want to use pdqsort.

Is that OK from your side @orlp or would you rather not include anything like that in your repo?

**Comment by orlp** [comment]
No thank you, I don't want to ship any particular package manager/build system. My library is a single header file you can include in your codebase.

**Comment by damageboy** [comment]
Thanks for the quick response!
