### ISSUE TITLE
Branchless Lomuto

### ISSUE THREAD

**Issue by RedBedHed** [orlp/pdqsort#26]
Hi Orson,

My name is Ellie. 

I am a computer science graduate saving to return to school, and I have some extra time on my hands. I am primarily interested in researching AI but also dabble in sorting. I make money working on embedded systems, where memory overhead discourages most library authors from using quicksort. I am attempting to write a generic library sort in C for these systems (with no more than 30*8 bytes of static RAM for the interval stack, preferably less).

During my embedded sorting journey, I've written many branchful pdqsort variants. I've even sped things up slightly with 2-3 pivot partitioning. Still, I couldn't compete with state-of-the-art partitioning schemes like block partitioning. I couldn't use them either, as they seemed to require significant (albeit constant) extra memory.

A few nights ago, I was thrilled to read your blog post and Lukas Bergdoll's write-up on branchless Lomuto partitioning, and I needed to try it for myself. Of course, nothing could have prepared me for its actual performance (on arrays of integers, at least). It is safe to say it blew me away.

I found that a pdqsort variant with branchless Lomuto can outperform the current pdqsort on several patterns in your benchmark, most notably shuffled data. 

As you know, Lomuto partitioning does suffer on descending data. However, I also found that swap-rotating data when it is likely descending seems to remedy this without significantly affecting performance on the other patterns.

I think it would be very cool if you could incorporate your Lomuto partitioning into your pdqsort (for integer types).

[Here is my little experiment](https://github.com/RedBedHed/blipsort) (There may be semantic errors. I haven't slept in a bit lol.)

Cheers,

Ellie

**Comment by orlp** [comment]
I think I want to preserve pdqsort as it is now. Too many things refer to it at this point, expecting certain characteristics. I don't want to invalidate all those things by changing what it does rather fundamentally (especially because the Lomuto partition is worse for types that have expensive moves).
